### ISSUE TITLE
Comments on Affective Conflict Resolution Task

### ISSUE THREAD

**Issue by danieljwilson** [JuneOh710/affective-conflict-resolution-task#1]
## Launch

Opens on directory instead of starting task:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/7377893/156536261-e11b899d-7204-427e-8ad4-1e4d2996dbbf.png">

I think this is because you may need to have a `index.html` naming of your main file...

## Practice Round
Good overall.

- Some of the inter trial intervals are quite short. What is the minimum length you are using, and what is the range?
- [x] Could you add text indicating "Correct" and "Incorrect" in green and red for each response?

## Warning page
- [x] Could you make the text a bit larger?

## Trials
- [x] Just checking - are the response buttons in the same position as in the practice?
- [x] Are the button placement locations randomized between subjects? (i.e. each time you launch an instance of the task)
- [x] We do have scared facial expressions included in the photos? Not really able to tell...

## Task Completion
- [x] Nothing happens when I press the button, should something?
- [x] Same question as with other tasks - no .csv file auto-created?
